TiendaVirtual.Web/ViewModels/Cliente/ClienteEditVm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TiendaVirtual.Web.ViewModels.Cliente
{
    public class ClienteEditVm
    {
        public int Id { get; set; }
        [DisplayName("Cliente")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(100, ErrorMessage = "El campo {0} debe contener entre {2} y {1} caracteres", MinimumLength = 3)]
        public string Nombre { get; set; }
        [DisplayName("Dirección")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(100, ErrorMessage = "El campo {0} debe contener entre {2} y {1} caracteres", MinimumLength = 3)]

        public string Direccion { get; set; }
        [DisplayName("Pais")]
        [Range(1, int.MaxValue, ErrorMessage = "Debe seleccionar un país")]

        public int PaisId { get; set; }
        [DisplayName("Ciudad")]
        [Range(1, int.MaxValue, ErrorMessage = "Debe seleccionar un país")]

        public int CiudadId { get; set; }
        public string CodPostal { get; set; }
        [DisplayName("Tel. Fijo")]
        [MaxLength(20, ErrorMessage = "El campo {0} no puede tener más de {1} caracteres")]
        public string TelefonoFijo { get; set; }
        [DisplayName("Tel. Móvil")]
        [MaxLength(20, ErrorMessage = "El campo {0} no puede tener más de {1} caracteres")]

        public string TelefonoMovil { get; set; }

        
        [MaxLength(256, ErrorMessage = "El campo {0} no puede tener más de {1} caracteres")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        public string EmailAnterior { get; set; }
        public byte[] RowVersion { get; set; }

        public List<SelectListItem> Paises { get; set; }
        public List<SelectListItem> Ciudades { get; set; }


    }
}

TiendaVirtual.Web/ViewModels/Cliente/ClienteListSortVm.cs
using PagedList;
using System.Collections.Generic;

namespace TiendaVirtual.Web.ViewModels.Cliente
{
    public class ClienteListSortVm
    {
        public IPagedList<ClienteListVm> Clientes { get; set; }
        public string SortBy { get; set; }
        public Dictionary<string, string> Sorts { get; set; }
        public string SearchBy { get; set; }
    }
}

TiendaVirtual.Web/ViewModels/Cliente/ClienteListVm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace TiendaVirtual.Web.ViewModels.Cliente
{
    public class ClienteListVm
    {
        public int ClienteId { get; set; }
        [DisplayName("Cliente")]
        public string NombreCliente { get; set; }
        public string Pais { get; set; }
        public string Ciudad { get; set; }

    }
}

TiendaVirtual.Web/Controllers/ClientesController.cs
using AutoMapper;
using PagedList;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using System.Web.Mvc;
using TiendaVirtual.Entidades.Entidades;
using TiendaVirtual.Servicios.Interfaces;
using TiendaVirtual.Web.App_Start;
using TiendaVirtual.Web.Helpers;
using TiendaVirtual.Web.ViewModels.Ciudad;
using TiendaVirtual.Web.ViewModels.Cliente;

namespace TiendaVirtual.Web.Controllers
{
    public class ClientesController : Controller
    {
        private readonly IServiciosClientes _servicios;
        private readonly IServiciosPaises _serviciosPaises;
        private readonly IServiciosCiudades _serviciosCiudades;
        private readonly IMapper _mapper;
        public ClientesController(IServiciosClientes servicios,
            IServiciosPaises serviciosPaises,
            IServiciosCiudades serviciosCiudades)
        {
            _servicios = servicios;
            _serviciosPaises= serviciosPaises;
            _serviciosCiudades= serviciosCiudades;
            _mapper = AutoMapperConfig.Mapper;
        }
        // GET: Clientes
        public ActionResult Index(int? page, int? pageSize, string SortBy="Cliente", string SearchBy=null)
        {
            page= page ?? 1;
            pageSize= pageSize ?? 10;
            var lista=_servicios.GetClientes();
            if (SearchBy!=null)
            {
                lista=lista
                    .Where(c=>c.NombreCliente.Contains(SearchBy)|| c.Pais.Contains(SearchBy))
                    .ToList();
            }

            var listaVm = _mapper.Map<List<ClienteListVm>>(lista);
            if (SortBy == "Cliente")
            {
                listaVm=listaVm.OrderBy(c=>c.NombreCliente).ToList();
            }else
            {
                listaVm=listaVm.OrderBy(c=>c.Pais).ThenBy(c=>c.Ciudad).ToList();
            }
            var clienteVm = new ClienteListSortVm
            {
                Clientes = listaVm.ToPagedList(page.Value, pageSize.Value),
                Sorts = new Dictionary<string, string> {
                    {"Por Cliente","Cliente"},
                    {"Por País","Pais" }
                },
                SortBy = SortBy,
                SearchBy = SearchBy
            };

            return View(clienteVm);
        }

        public ActionResult Create()
        {
            var clienteVm = new ClienteEditVm
            {
                Paises = _serviciosPaises.GetPaisesDropDownList(),
                Ciudades = new List<SelectListItem>()

            };
            return View(clienteVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ClienteEditVm clienteVm)
        {
            if (!ModelState.IsValid)
            {
                clienteVm.Paises = _serviciosPaises.GetPaisesDropDownList();
                clienteVm.Ciudades = _serviciosCiudades.GetCiudadesDropDownList(clienteVm.PaisId);
                return View(clienteVm);
            }
            try
            {
                var cliente = _mapper.Map<Cliente>(clienteVm);
                if (!_servicios.Existe(cliente))
                {
                    using(var tran=new TransactionScope())
                    {
                        _servicios.Guardar(cliente);
                        UsersHelper.CreateUserAsp(cliente.Email, "Cliente");
                        tran.Complete();
                    }
                    TempData["Msg"] = "Registro agregado satisfactoriamente";
                    return RedirectToAction("Index");

                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Cliente existente!!!");
                    clienteVm.Paises = _serviciosPaises.GetPaisesDropDownList();
                    clienteVm.Ciudades = _serviciosCiudades.GetCiudadesDropDownList(clienteVm.PaisId);

                    return View(clienteVm);
                }
            }
            catch (System.Exception)
            {

                ModelState.AddModelError(string.Empty, "Error al intentar agregar un Cliente");
                clienteVm.Paises = _serviciosPaises.GetPaisesDropDownList();
                clienteVm.Ciudades = _serviciosCiudades.GetCiudadesDropDownList(clienteVm.PaisId);

                return View(clienteVm);
            }
        }

        public ActionResult Edit(int? id)
        {
            if (id==null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var cliente = _servicios.GetClientePorId(id.Value);
            if (cliente==null)
            {
                return HttpNotFound("Cód. de cliente inexistente!!!");
            }
            var clienteVm = _mapper.Map<ClienteEditVm>(cliente);
            clienteVm.Paises = _serviciosPaises.GetPaisesDropDownList();
            clienteVm.Ciudades = _serviciosCiudades.GetCiudadesDropDownList(cliente.PaisId);
            return View(clienteVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ClienteEditVm clienteVm)
        {
            if (!ModelState.IsValid)
            {
                clienteVm.Paises = _serviciosPaises.GetPaisesDropDownList();
                clienteVm.Ciudades = _serviciosCiudades.GetCiudadesDropDownList(clienteVm.PaisId);
                return View(clienteVm);

            }
            try
            {
                var cliente = _mapper.Map<Cliente>(clienteVm);
                if (!_servicios.Existe(cliente))
                {
                    using(var tran=new TransactionScope())
                    {
                        _servicios.Guardar(cliente);
                        //Preguntar que paso
                        UsersHelper.UpdateUserName(clienteVm.EmailAnterior, cliente.Email);
                        tran.Complete();
                    }
                    TempData["Msg"] = "Registro editado satisfactoriamente";
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Cliente existente!!!");
                    clienteVm.Paises = _serviciosPaises.GetPaisesDropDownList();
                    clienteVm.Ciudades = _serviciosCiudades.GetCiudadesDropDownList(clienteVm.PaisId);
                    return View(clienteVm);

                }
            }
            catch (System.Exception)
            {
                ModelState.AddModelError(string.Empty, "Cliente existente!!!");
                clienteVm.Paises = _serviciosPaises.GetPaisesDropDownList();
                clienteVm.Ciudades = _serviciosCiudades.GetCiudadesDropDownList(clienteVm.PaisId);
                return View(clienteVm);
            }
        }

        public ActionResult Delete(int? id)
        {
            if (id==null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var cliente = _servicios.GetClientePorId(id.Value);
            if (cliente==null)
            {
                return HttpNotFound("Cód. cliente inexistente!!!");
            }
            var clienteVm=_mapper.Map<ClienteListVm>(cliente);
            return View(clienteVm);
        }

        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int id)
        {
            var cliente = _servicios.GetClientePorId(id);
            var clienteVm = _mapper.Map<ClienteListVm>(cliente);
            try
            {
                if (!_servicios.EstaRelacionado(cliente))
                {
                    _servicios.Borrar(id);
                    TempData["Msg"] = "Cliente borrado satisfactoriamente";
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Registro relacionado... Baja denegada");
                    return View(clienteVm);
                }
            }
            catch (System.Exception)
            {

                ModelState.AddModelError(string.Empty, "Error al intengar borrar un cliente");
                return View(clienteVm);

            }
        }

    }
}

TiendaVirtual.Web/Controllers/GenericoController.cs
using AutoMapper;
using System.Collections.Generic;
using System.Web.Mvc;
using TiendaVirtual.Servicios.Interfaces;
using TiendaVirtual.Web.App_Start;
using TiendaVirtual.Web.ViewModels.Ciudad;

namespace TiendaVirtual.Web.Controllers
{
    public class GenericoController : Controller
    {
        // GET: Generico
        private readonly IServiciosCiudades _serviciosCiudades;
        private readonly IMapper _mapper;
        public GenericoController(IServiciosCiudades serviciosCiudades)
        {
            _serviciosCiudades = serviciosCiudades;
            _mapper = AutoMapperConfig.Mapper;
        }
        public JsonResult GetCities(int paisId)
        {
            var lista = _serviciosCiudades.GetCiudades(paisId);
            var ciudadesVm = _mapper.Map<List<CiudadListVm>>(lista);
            return Json(ciudadesVm);
        }
    }
}

TiendaVirtual.Web/Views/Clientes/Create.cshtml
@model TiendaVirtual.Web.ViewModels.Cliente.ClienteEditVm

@{
    ViewBag.Title = "Create";
}

<h2>Agregar Cliente</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("_MostrarCliente", Model)
        <div class="form-group mt-3">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-success" })
            </div>
        </div>


    </div>
}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        var Url = '@Url.Action("GetCities", "Generico")';
    </script>
}

TiendaVirtual.Web/Views/Clientes/Delete.cshtml
@model TiendaVirtual.Web.ViewModels.Cliente.ClienteListVm

@{
    ViewBag.Title = "Delete";
}

<h2>Borrar Cliente</h2>

<h3>¿Está seguro de borrar el cliente mostrado?</h3>
@Html.ValidationSummary(true, "", new { @class = "text-danger" })
@Html.HiddenFor(model=>model.ClienteId)
<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.NombreCliente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreCliente)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ciudad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ciudad)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-danger" /> |
            @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-success" })
        </div>
    }
</div>

TiendaVirtual.Web/Views/Clientes/Edit.cshtml
@model TiendaVirtual.Web.ViewModels.Cliente.ClienteEditVm

@{
    ViewBag.Title = "Edit";
}

<h2>Editar Cliente</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.RowVersion)
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("_MostrarCliente", Model)
        <div class="form-group mt-3">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Editar" class="btn btn-warning" />
                @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-success" })
            </div>
        </div>
    </div>
}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        var Url = '@Url.Action("GetCities", "Generico")';
    </script>
}

TiendaVirtual.Web/Views/Clientes/Index.cshtml
@using PagedList.Mvc
@model TiendaVirtual.Web.ViewModels.Cliente.ClienteListSortVm

@{
    ViewBag.Title = "Index";
}
<div class="d-flex justify-content-between">
    <h2>Lista de Clientes</h2>

    <p>
        @Html.ActionLink("Nuevo", "Create", null, new { @class = "btn btn-primary" })
    </p>

</div>
@using (Html.BeginForm("Index", "Clientes", FormMethod.Get))
{
    <div class="row">
        <div class="col-auto">
            <label>Ordenar:</label>
        </div>
        <div class="col-auto">
            @Html.DropDownListFor(model => Model.SortBy, new SelectList(Model.Sorts, "Value", "Key"), "Seleccione Orden", new { @class = "form-select" })
        </div>
        <div class="col-auto">
            <input type="text" placeholder="Buscar...." name="SearchBy" class="form-control" />
        </div>
        <div class="col-auto">
            <input type="submit" name="SortBy" value="Aplicar" class="btn btn-secondary" />
        </div>
    </div>

}
<table class="table table-bordered table-hover mt-3">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Clientes.FirstOrDefault().NombreCliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Clientes.FirstOrDefault().Pais)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Clientes.FirstOrDefault().Ciudad)
        </th>
        <th>Acciones</th>
    </tr>

    @foreach (var item in Model.Clientes)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NombreCliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pais)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ciudad)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ClienteId }, new { @class = "btn btn-warning" })
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }, new { @class = "btn btn-info" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ClienteId }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>
Página: @(Model.Clientes.PageCount < Model.Clientes.PageNumber ? 0 : Model.Clientes.PageNumber) de: @Model.Clientes.PageCount
@Html.PagedListPager(Model.Clientes, page => Url.Action("Index", new
{
    page,
    pageSize = ViewBag.PageSize,
    SortBy=Model.SortBy,
    SearchBy=Model.SearchBy
}))