TiendaVirtual.Web/Controllers/CarritoController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using TiendaVirtual.Entidades.Entidades;
using TiendaVirtual.Entidades.Enums;
using TiendaVirtual.Servicios;
using TiendaVirtual.Servicios.Interfaces;
using TiendaVirtual.Web.App_Start;
using TiendaVirtual.Web.Models.Carrito;
using TiendaVirtual.Web.ViewModels.Carrito;

namespace TiendaVirtual.Web.Controllers
{
    public class CarritoController : Controller
    {
        // GET: Carrito
        private readonly IServiciosCarrito _serviciosCarritos;
        private readonly IServiciosProductos _serviciosProductos;
        private readonly IServiciosClientes _serviciosClientes;
        private readonly IServiciosVentas _serviciosVentas;
        private readonly IMapper _mapper;
        public CarritoController(IServiciosProductos serviciosProductos,
            IServiciosCarrito serviciosCarritos,
            IServiciosClientes serviciosClientes,
            IServiciosVentas serviciosVentas)
        {
            _serviciosProductos = serviciosProductos;
            _mapper = AutoMapperConfig.Mapper;
            _serviciosCarritos = serviciosCarritos;
            _serviciosClientes = serviciosClientes;
            _serviciosVentas = serviciosVentas;
        }

        private Carrito _carrito;

        public ActionResult Index(string returnUrl)
        {
            _carrito = GetCarrito();
            if (_carrito.GetCantidad() == 0)
            {
                return View("EmptyCart");
            }
            var listaItem = _carrito.GetItems();
            var listaItemVm = _mapper.Map<List<ItemCarritoVm>>(listaItem);

            CarritoVm carritoVm = new CarritoVm
            {
                Items = listaItemVm,
                returnUrl = returnUrl
            };
            return View(carritoVm);
        }
        public ActionResult MostrarCarrito()
        {
            _carrito = GetCarrito();

            return PartialView("_MostrarCarrito", _carrito);
        }

        private Carrito GetCarrito()
        {
            if (_carrito != null)
            {
                return _carrito;
            }
            _carrito = (Carrito)Session["carrito"];
            if (_carrito == null)
            {
                _carrito = new Carrito();
                Session["carrito"] = _carrito;
            }

            if (_carrito.GetCantidad() == 0)
            {
                if (_serviciosCarritos.GetCantidad(User.Identity.Name) > 0)
                {
                    var listaItemsCarrito = _serviciosCarritos
                        .GetCarrito(User.Identity.Name);
                    foreach (var item in listaItemsCarrito)
                    {
                        _carrito.AddToCart(item);
                    }
                    Session["carrito"] = _carrito;
                }

            }
            return _carrito;
        }

        [HttpPost]
        public ActionResult AddToCart(int productoId, string returnUrl, int cantidad = 1)
        {
            var productoDto = _serviciosProductos.GetProductoPorId(productoId);
            if (productoDto.Stock >= cantidad)
            {
                ItemCarrito itemCarrito = new ItemCarrito
                {
                    ProductoId = productoDto.ProductoId,
                    UserName = User.Identity.Name,
                    NombreProducto = productoDto.NombreProducto,
                    PrecioUnitario = productoDto.PrecioUnitario,
                    Cantidad = cantidad,

                };
                _carrito = GetCarrito();
                _carrito.AddToCart(itemCarrito);
                Session["carrito"] = _carrito;
                _serviciosCarritos.Guardar(itemCarrito);
                _serviciosProductos.ActualizarUnidadesEnPedido(productoId, cantidad);
                return RedirectToAction("Index", new { returnUrl });

            }
            else
            {
                TempData["Error"] = "Cantidad mayor al stock";
                return RedirectToAction("Index", new { returnUrl });
            }
        }

        public ActionResult RemoveFromCart(int productoId, string returnUrl)
        {
            _carrito = GetCarrito();
            _carrito.RemoveFromCart(productoId);
            Session["carrito"] = _carrito;
            _serviciosCarritos.Borrar(User.Identity.Name, productoId);
            return RedirectToAction("Index", new { returnUrl });

        }

        public ActionResult CancelOrder()
        {
            //TODO: Hacer lo que falta de la cancelación
            _carrito = GetCarrito();
            foreach (var item in _carrito.GetItems())
            {
                _serviciosCarritos.Borrar(User.Identity.Name, item.ProductoId);
            }
            _carrito.Clear();
            Session["carrito"] = _carrito;

            return View();
        }

        public ActionResult ConfirmOrder(string returnUrl)
        {
            //TODO: Hacer la confirmación de la orden
            _carrito = GetCarrito();
            if (_carrito.GetCantidad() == 0)
            {
                return View("EmptyCart");
            }
            var listaItem = _carrito.GetItems();
            var listaItemVm = _mapper.Map<List<ItemCarritoVm>>(listaItem);

            CarritoVm carritoVm = new CarritoVm
            {
                Items = listaItemVm,
                returnUrl = returnUrl
            };
            CheckOutVm model = new CheckOutVm()
            {
                Carrito = carritoVm,
                //Meses = PaymentHelper.GetMeses(),
                //Anios = PaymentHelper.GetAnios(),
            };
            //model.Meses = PaymentHelper.GetMeses();
            //model.Anios = PaymentHelper.GetAnios();
            return View(model);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ConfirmOrder(CheckOutVm model)
        {
            _carrito = GetCarrito();
            var listaItem = _carrito.GetItems();
            var listaItemVm = _mapper.Map<List<ItemCarritoVm>>(listaItem);

            CarritoVm carritoVm = new CarritoVm
            {
                Items = listaItemVm,
            };
            model.Carrito = carritoVm;
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            PaymentResult resultado = CheckOut(model);
            if (resultado.Exitoso)
            {
                TempData["TransaccionId"] = resultado.TransaccionId;
                return RedirectToAction("Complete");
            }
            ModelState.AddModelError(string.Empty, resultado.Mensaje);
            return View(model);

        }
        private PaymentResult CheckOut(CheckOutVm model)
        {
            Cliente cliente = _serviciosClientes.GetClientePorEmail(User.Identity.Name);
            var venta = new Venta()
            {
                ClienteId = cliente.Id,
                FechaVenta = DateTime.Now,
                Estado = Estado.Impaga,
                Total = _carrito.GetTotal()
            };
            foreach (var item in model.Carrito.Items)
            {
                DetalleVenta detalleVenta = new DetalleVenta()
                {

                    ProductoId = item.ProductoId,
                    Cantidad = item.Cantidad,
                    PrecioUnitario = item.PrecioUnitario,

                };
                venta.Detalles.Add(detalleVenta);
            }
            //TODO:Autorizar el pago
            var checkout = new CheckOut()
            {
                Venta = venta,
                CardNumber = model.CardNumber,
                CVV = model.CVV,
                Month = model.Month,
                Year = model.Year,
            };
            var gateway = new PaymentGateway();
            var resultado = gateway.ProcesarPago(checkout);
            if (resultado.Exitoso)
            {
                _carrito = GetCarrito();
                _carrito.Clear();
                Session["carrito"] = _carrito;

                venta.TransaccionId = resultado.TransaccionId;
                _serviciosVentas.Guardar(venta, User.Identity.Name);

            }
            //TODO:Obtener TransaccionId
            return resultado;
        }

        public ActionResult Complete()
        {
            ViewBag.TransaccionId = (string)TempData["TransaccionId"];
            return View();
        }
    }
}

TiendaVirtual.Web/Controllers/ProductosController.cs
using AutoMapper;
using Neptuno2022EF.Servicios.Servicios;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using TiendaVirtual.Entidades.Dtos.Ciudad;
using TiendaVirtual.Entidades.Dtos.Producto;
using TiendaVirtual.Entidades.Entidades;
using TiendaVirtual.Servicios.Interfaces;
using TiendaVirtual.Utilidades;
using TiendaVirtual.Web.App_Start;
using TiendaVirtual.Web.ViewModels.Ciudad;
using TiendaVirtual.Web.ViewModels.Producto;

namespace TiendaVirtual.Web.Controllers
{
    public class ProductosController : Controller
    {
        private readonly IServiciosProductos _servicios;
        private readonly IServiciosProveedores _serviciosProveedores;
        private readonly IServiciosCategorias _serviciosCategorias;
        private readonly IMapper _mapper;
        public ProductosController(IServiciosProductos servicios,
            IServiciosProveedores serviciosProveedores,
            IServiciosCategorias serviciosCategorias)
        {
            _servicios = servicios;
            _serviciosProveedores = serviciosProveedores;
            _serviciosCategorias = serviciosCategorias;
            _mapper = AutoMapperConfig.Mapper;
        }
        // GET: Productos
        public ActionResult Index(int? CategoriaFiltro, int? page, int? pageSize)
        {
            List<ProductoListDto> lista=null;
            if (User.IsInRole("Cliente") ||(User.Identity.Name==string.Empty))
            {
                if (CategoriaFiltro == null)
                {
                    Func<Producto, bool> predicado = p => (p.UnidadesEnPedido > 0 || p.Suspendido == false);
                    lista = _servicios.Filtrar(predicado);

                }
                else
                {
                    Func<Producto, bool> predicado = p => (p.UnidadesEnPedido > 0 && p.Suspendido == false) && p.CategoriaId==CategoriaFiltro.Value ;
                    lista = _servicios.Filtrar(predicado);

                }
            }
            else if(User.IsInRole("Admin"))
            {
                lista = _servicios.GetProductos(true);
            }
            
            var listaVm = _mapper.Map<List<ProductoListVm>>(lista);
            page = page ?? 1;
            pageSize = pageSize ?? 8;

            var productoVm = new ProductoFiltroVm
            {
                CategoriaFiltro=CategoriaFiltro,
                Categorias=_serviciosCategorias.GetCategoriasDropDownList(),
                Productos = listaVm.ToPagedList(page.Value, pageSize.Value)
            };
            return View(productoVm);

        }

        public ActionResult Create()
        {
            var productoVm = new ProductoEditVm
            {
                Proveedores = _serviciosProveedores.GetProveedoresDropDownList(),
                Categorias = _serviciosCategorias.GetCategoriasDropDownList()

            };
            return View(productoVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductoEditVm productoVm)
        {
            if (!ModelState.IsValid)
            {
                productoVm.Proveedores = _serviciosProveedores.GetProveedoresDropDownList();
                productoVm.Categorias = _serviciosCategorias.GetCategoriasDropDownList();
                return View(productoVm);
            }
            try
            {
                var producto = _mapper.Map<Producto>(productoVm);
                if (!_servicios.Existe(producto))
                {
                    if (productoVm.imagenFile != null)
                    {
                        string extension = Path.GetExtension(productoVm.imagenFile.FileName);
                        string filename = Guid.NewGuid().ToString();

                        var file = $"{filename}{extension}";
                        var response = FileHelper.UploadPhoto(productoVm.imagenFile, WC.ProductosImagenesFolder, file);
                        producto.Imagen = file;
                    }

                    _servicios.Guardar(producto);
                    TempData["Msg"] = "Registro agregado satisfactoriamente";
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Producto existente!!!");
                    productoVm.Proveedores = _serviciosProveedores.GetProveedoresDropDownList();
                    productoVm.Categorias = _serviciosCategorias.GetCategoriasDropDownList();

                    return View(productoVm);
                }
            }
            catch (System.Exception)
            {

                ModelState.AddModelError(string.Empty, "Error al intentar agregar un Producto");
                productoVm.Proveedores = _serviciosProveedores.GetProveedoresDropDownList();
                productoVm.Categorias = _serviciosCategorias.GetCategoriasDropDownList();

                return View(productoVm);
            }
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var producto = _servicios.GetProductoPorId(id.Value);
            if (producto == null)
            {
                return HttpNotFound("Cód. de proveedor inexistente!!!");
            }
            var productoVm = _mapper.Map<ProductoEditVm>(producto);
            productoVm.Proveedores = _serviciosProveedores.GetProveedoresDropDownList();
            productoVm.Categorias = _serviciosCategorias.GetCategoriasDropDownList();
            return View(productoVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductoEditVm productoVm)
        {
            if (!ModelState.IsValid)
            {
                productoVm.Proveedores = _serviciosProveedores.GetProveedoresDropDownList();
                productoVm.Categorias = _serviciosCategorias.GetCategoriasDropDownList();
                return View(productoVm);

            }
            try
            {
                var producto = _mapper.Map<Producto>(productoVm);
                if (!_servicios.Existe(producto))
                {
                    _servicios.Guardar(producto);
                    TempData["Msg"] = "Registro editado satisfactoriamente";
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Producto existente!!!");
                    productoVm.Proveedores = _serviciosProveedores.GetProveedoresDropDownList();
                    productoVm.Categorias = _serviciosCategorias.GetCategoriasDropDownList();
                    return View(productoVm);

                }
            }
            catch (System.Exception)
            {
                ModelState.AddModelError(string.Empty, "Producto existente!!!");
                productoVm.Proveedores = _serviciosProveedores.GetProveedoresDropDownList();
                productoVm.Categorias = _serviciosCategorias.GetCategoriasDropDownList();
                return View(productoVm);
            }
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var producto = _servicios.GetProductoPorId(id.Value);
            if (producto == null)
            {
                return HttpNotFound("Cód. producto inexistente!!!");
            }
            var productoVm = _mapper.Map<ProductoListVm>(producto);
            return View(productoVm);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int id)
        {
            var producto = _servicios.GetProductoPorId(id);
            var productoVm = _mapper.Map<ProductoListVm>(producto);
            try
            {
                if (!_servicios.EstaRelacionado(producto))
                {
                    _servicios.Borrar(id);
                    TempData["Msg"] = "Producto borrado satisfactoriamente";
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Registro relacionado... Baja denegada");
                    return View(productoVm);
                }
            }
            catch (System.Exception)
            {

                ModelState.AddModelError(string.Empty, "Error al intengar borrar un proveedor");
                return View(productoVm);

            }
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var producto = _servicios.GetProductoPorId(id.Value);
            if (producto == null)
            {
                return HttpNotFound("Cód. producto inexistente!!!");
            }
            var productoVm = _mapper.Map<ProductoListVm>(producto);
            return View(productoVm);
        }
    }
}

TiendaVirtual.Web/Views/Productos/Create.cshtml
@model TiendaVirtual.Web.ViewModels.Producto.ProductoEditVm

@{
    ViewBag.Title = "Create";
}

<h2>Nuevo Producto</h2>

@using (Html.BeginForm("Create", "Productos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.Partial("_MostrarProducto", Model)




    <div class="form-group mt-3">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-primary" />
            @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-success" })
        </div>
    </div>
</div>
}

<div>
</div>

TiendaVirtual.Web/Views/Productos/Delete.cshtml
@model TiendaVirtual.Web.ViewModels.Producto.ProductoListVm

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProductoListVm</h4>
    <hr />
    <div class="row">
        <div class="col-8">
            <dl class="dl-horizontal">

                <dt>
                    @Html.DisplayNameFor(model => model.NombreProducto)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.NombreProducto)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Categoria)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Categoria)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.PrecioUnitario)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PrecioUnitario)
                </dd>


                <dt>
                    @Html.DisplayNameFor(model => model.Suspendido)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Suspendido)
                </dd>


            </dl>
        </div>
        <div class="col-4">

            <div class="form-group">
                @Html.DisplayNameFor(model => model.Imagen)
                @if (Model.Imagen != null)
                {
                    <img src="@Url.Content(TiendaVirtual.Utilidades.WC.ProductosImagenesFolder+Model.Imagen)" style="width:100px; height:100px" />
                }
                else
                {
                    <img src="@Url.Content(TiendaVirtual.Utilidades.WC.SinImagenDisponible)" style="width:100px; height:100px" />

                }
            </div>


        </div>
    </div>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-danger" /> |
            @Html.ActionLink("Volver", "Index",null,new {@class="btn btn-success"})
        </div>
    }
</div>

TiendaVirtual.Web/Views/Productos/Details.cshtml
@model TiendaVirtual.Web.ViewModels.Producto.ProductoListVm
@{
    ViewBag.Title = "Details";
}

<h2>Detalle del Producto</h2>
<!-- Product section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            @if (Model.Imagen == null)
            {
                <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="@Url.Content(TiendaVirtual.Utilidades.WC.SinImagenDisponible)" style="width:500px; height:500px" /></div>

            }
            else
            {
                <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="@Url.Content(TiendaVirtual.Utilidades.WC.ProductosImagenesFolder+Model.Imagen)" style="width:500px; height:500px" /></div>

            }
            <div class="col-md-6">
                <div class="small mb-1">@Model.Categoria</div>
                <h1 class="display-5 fw-bolder">@Model.NombreProducto</h1>
                <div class="fs-5 mb-5">
                    <span class="text-decoration-line-through">@(Model.PrecioUnitario+10)</span>
                    <span>@Model.PrecioUnitario</span>
                </div>
                <p class="lead">Stock:<strong>@Model.UnidadesDisponibles</strong> </p>
                @using (Html.BeginForm("AddToCart", "Carrito", FormMethod.Post))
                {
                    <div class="d-flex">
                        @Html.Hidden("productoId", Model.ProductoId)
                        @Html.Hidden("returnUrl", "/Productos/")
                        <input class="form-control text-center me-3" name="cantidad" id="inputQuantity" type="num" value="1" style="max-width: 3rem" />
                        <button class="btn btn-outline-dark flex-shrink-0 me-3" type="submit">
                            <i class="fa fa-shopping-cart me-1"></i>
                            Comprar
                        </button>

                        @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-success" })


                    </div>
                }
            </div>
        </div>
    </div>
</section>

TiendaVirtual.Web/Views/Productos/Edit.cshtml
@model TiendaVirtual.Web.ViewModels.Producto.ProductoEditVm

@{
    ViewBag.Title = "Edit";
}

<h2>Editar Producto</h2>

@using (Html.BeginForm("Edit", "Productos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        @Html.HiddenFor(model=>model.ProductoId)
        @Html.HiddenFor(model=>model.RowVersion)
        @Html.HiddenFor(model=>model.imagenFile)

        @Html.Partial("_MostrarProducto",Model)


        <div class="form-group mt-3">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-warning" />
                @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-success" })
            </div>
        </div>
    </div>
}

TiendaVirtual.Web/Views/Productos/Index.cshtml
@using PagedList.Mvc
@model TiendaVirtual.Web.ViewModels.Producto.ProductoFiltroVm

@{
    ViewBag.Title = "Index";
}
<div class="d-flex justify-content-between">
    <h2>Listado de Productos</h2>
    @if (User.IsInRole("Admin"))
    {
        <p>
            @Html.ActionLink("Nuevo", "Create", null, new { @class = "btn btn-primary" })
        </p>

    }

</div>
@using (Html.BeginForm("Index", "Productos", FormMethod.Get))
{
    <div class="row">
        <div class="col-auto">
            <label>Categorías:</label>
        </div>
        <div class="col-auto">
            @Html.DropDownListFor(model => model.CategoriaFiltro, Model.Categorias, "Ver Todos", new { @class = "form-select" })
        </div>
        <div class="col-auto">
            <input type="submit" value="Filtrar" class="btn btn-secondary" />
        </div>
    </div>
}

<table class="table table-bordered table-hover mt-3">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Productos[0].Imagen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Productos[0].NombreProducto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Productos[0].Categoria)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Productos[0].PrecioUnitario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Productos[0].UnidadesDisponibles)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Productos[0].Suspendido)
        </th>
        @if (User.IsInRole("Admin") || User.IsInRole("Cliente"))
        {
            <th></th>

        }
    </tr>

    @foreach (var item in Model.Productos)
    {
        <tr>
            <td>
                @if (item.Imagen != null)
                {
                    <img src="@Url.Content(TiendaVirtual.Utilidades.WC.ProductosImagenesFolder+item.Imagen)" style="width:50px; height:50px" />
                }
                else
                {
                    <img src="@Url.Content(TiendaVirtual.Utilidades.WC.SinImagenDisponible)" style="width:50px; height:50px" />

                }

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombreProducto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Categoria)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrecioUnitario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UnidadesDisponibles)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Suspendido)
            </td>
            @if (User.IsInRole("Admin") || User.IsInRole("Cliente"))
            {
                <td>
                    @if (User.IsInRole("Admin"))
                    {
                        @Html.ActionLink("Editar", "Edit", new { id = item.ProductoId }, new { @class = "btn btn-warning" })
                        @Html.ActionLink("Detalles", "Details", new { id = item.ProductoId }, new { @class = "btn btn-info" })
                        @Html.ActionLink("Borrar", "Delete", new { id = item.ProductoId }, new { @class = "btn btn-danger" })
                    }
                    @if (User.IsInRole("Cliente"))
                    {
                        using (Html.BeginForm("AddToCart", "Carrito", FormMethod.Post))
                        {
                            @Html.ActionLink("Detalles", "Details", new { id = item.ProductoId }, new { @class = "btn btn-info" })

                            @Html.Hidden("productoId", item.ProductoId)
                            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                            <button type="submit" class="btn btn-outline-danger">
                                Comprar
                            </button>

                        }


                    }

                </td>

            }
        </tr>
    }

</table>
    Página: @(Model.Productos.PageCount < Model.Productos.PageNumber ? 0 : Model.Productos.PageNumber) de: @Model.Productos.PageCount
    @Html.PagedListPager(Model.Productos, page => Url.Action("Index", new
    {
        CategoriaFiltro = Model.CategoriaFiltro,
        page,
        pageSize = ViewBag.PageSize
    }))