TiendaVirtual.Web/Controllers/CiudadesController.cs
using AutoMapper;
using PagedList;
using System;
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;
using TiendaVirtual.Entidades.Dtos.Ciudad;
using TiendaVirtual.Entidades.Entidades;
using TiendaVirtual.Servicios.Interfaces;
using TiendaVirtual.Web.App_Start;
using TiendaVirtual.Web.ViewModels.Ciudad;

namespace TiendaVirtual.Web.Controllers
{
    public class CiudadesController : Controller
    {
        // GET: Ciudades
        private readonly IServiciosCiudades _servicio;
        private readonly IServiciosPaises _serviciosPaises;
        private readonly IMapper _mapper;
        public CiudadesController(IServiciosCiudades servicio, IServiciosPaises serviciosPaises)
        {
            _servicio = servicio;
            _mapper = AutoMapperConfig.Mapper;
            _serviciosPaises = serviciosPaises;

        }
        public ActionResult Index(int? PaisFiltro, int? page, int? pageSize)
        {
            List<CiudadListDto> lista;
            if (PaisFiltro==null)
            {
                lista = _servicio.GetCiudades();

            }
            else
            {
                lista = _servicio.GetCiudades(PaisFiltro.Value);
            }

            page = page ?? 1;
            pageSize = pageSize ?? 8;

            var listaVm = _mapper.Map<List<CiudadListVm>>(lista);
            var ciudadVm = new CiudadFiltroVm
            {
                PaisFiltro=PaisFiltro,
                Paises = _serviciosPaises.GetPaisesDropDownList(),
                Ciudades = listaVm.ToPagedList(page.Value, pageSize.Value)
            };
            return View(ciudadVm);
        }

        public ActionResult Create()
        {

            var ciudadVm = new CiudadEditVm()
            {
                Paises = _serviciosPaises.GetPaisesDropDownList(),
            };
            return View(ciudadVm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CiudadEditVm ciudadVm)
        {
            if (!ModelState.IsValid)
            {

                ciudadVm.Paises = _serviciosPaises.GetPaisesDropDownList();
                return View(ciudadVm);
            }
            var ciudad = _mapper.Map<Ciudad>(ciudadVm);
            if (_servicio.Existe(ciudad))
            {

                ciudadVm.Paises = _serviciosPaises.GetPaisesDropDownList();

                ModelState.AddModelError(string.Empty, "Ciudad existente!!!");
                return View(ciudadVm);
            }
            _servicio.Guardar(ciudad);
            TempData["Msg"] = "Registro guardado satisfactoriamente";
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var ciudad = _servicio.GetCiudadPorId(id.Value);
            if (ciudad == null)
            {
                return HttpNotFound("Código de ciudad inexistente!!!");
            }
            var ciudadVm = _mapper.Map<CiudadListVm>(ciudad);
            return View(ciudadVm);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int id)
        {
            var ciudad = _servicio.GetCiudadPorId(id);
            var ciudadVm = _mapper.Map<CiudadListVm>(ciudad);
            try
            {
                if (!_servicio.EstaRelacionada(ciudad))
                {
                    _servicio.Borrar(ciudad.CiudadId);
                    TempData["Msg"] = "Registro borrado satisfactoriamente";
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Ciudad relacionada... Baja denegada!!");
                    return View(ciudadVm);
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError(string.Empty, "Error al intentar borrar un registro de ciudades");
                return View(ciudadVm);

            }
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var ciudad = _servicio.GetCiudadPorId(id.Value);
            if (ciudad == null)
            {
                return HttpNotFound("Código de ciudad inexistente!!!");
            }
            var ciudadVm = _mapper.Map<CiudadEditVm>(ciudad);


            ciudadVm.Paises = _serviciosPaises.GetPaisesDropDownList();
            return View(ciudadVm);

        }
        [HttpPost]
        public ActionResult Edit(CiudadEditVm ciudadVm)
        {
            if (!ModelState.IsValid)
            {
                ciudadVm.Paises = _serviciosPaises.GetPaisesDropDownList();
                return View(ciudadVm);
            }
            try
            {
                var ciudad = _mapper.Map<Ciudad>(ciudadVm);
                if (!_servicio.Existe(ciudad))
                {
                    _servicio.Guardar(ciudad);
                    TempData["Msg"] = "Registro editado satisfactoriamente";
                    return RedirectToAction("Index");
                }
                else
                {
                    ciudadVm.Paises = _serviciosPaises.GetPaisesDropDownList();

                    ModelState.AddModelError(string.Empty, "Ciudad existente!!!");
                    return View(ciudadVm);
                }
            }
            catch (Exception)
            {
                ciudadVm.Paises = _serviciosPaises.GetPaisesDropDownList();

                ModelState.AddModelError(string.Empty, "Ciudad existente!!!");
                return View(ciudadVm);
            }
        }
    }
}

TiendaVirtual.Web/Controllers/PaisesController.cs
using AutoMapper;
using PagedList;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using TiendaVirtual.Entidades.Entidades;
using TiendaVirtual.Servicios.Interfaces;
using TiendaVirtual.Web.App_Start;
using TiendaVirtual.Web.ViewModels.Ciudad;
using TiendaVirtual.Web.ViewModels.Pais;

namespace TiendaVirtual.Web.Controllers
{
    
    public class PaisesController : Controller
    {
        // GET: Paises
        private readonly IServiciosPaises _servicios;
        private readonly IServiciosCiudades _serviciosCiudades;
        private readonly IMapper _mapper;
        public PaisesController(IServiciosPaises servicios, IServiciosCiudades serviciosCiudades)
        {
            _servicios = servicios;
            _serviciosCiudades = serviciosCiudades;
            _mapper = AutoMapperConfig.Mapper;
        }
        public ActionResult Index(int? page, int? pageSize)
        {
            var lista=_servicios.GetPaises();
            //var lista = new List<Pais>();
            //var listaVm=GetListaPaisesLstVm(lista);
            var listaVm=_mapper.Map<List<PaisListVm>>(lista);
            listaVm.ForEach(p => p.CantidadCiudades = _serviciosCiudades
                    .GetCantidad(c => c.PaisId == p.PaisId));
            page = page ?? 1;
            pageSize = pageSize ?? 10;
            ViewBag.PageSize=pageSize;
            return View(listaVm.ToPagedList(page.Value, pageSize.Value));
        }
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PaisEditVm paisVm)
        {
            if (ModelState.IsValid)
            {
                var pais = _mapper.Map<Pais>(paisVm);
                if (_servicios.Existe(pais))
                {
                    ModelState.AddModelError(string.Empty, "País existente!!!");
                    return View(paisVm);
                }
                _servicios.Guardar(pais);
                TempData["Msg"] = "Registro guardado satisfactoriamente";
                return RedirectToAction("Index");

            }
            else
            {
                return View(paisVm);
            }
        }

        public ActionResult Delete(int? id)
        {
            if (id==null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var pais = _servicios.GetPaisPorId(id.Value);
            if (pais == null)
            {
                return HttpNotFound("Código de país inesistente!!!");
            }
            var paisVm=_mapper.Map<PaisListVm> (pais);
            return View(paisVm);
        }

        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfim(int id) {
            var pais = _servicios.GetPaisPorId(id);
            if (_servicios.EstaRelacionado(pais))
            {
                var paisVm = _mapper.Map<PaisListVm>(pais);
                ModelState.AddModelError(string.Empty, "País relacionado... Baja denegada!!!");
                return View(paisVm);

            }
            _servicios.Borrar(id);
            TempData["Msg"] = "Registro borrado satisfactoriamente!!!";
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var pais = _servicios.GetPaisPorId(id.Value);
            if (pais == null)
            {
                return HttpNotFound("Código de país inesistente!!!");
            }
            var paisVm = _mapper.Map<PaisEditVm>(pais);
            return View(paisVm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PaisEditVm paisVm)
        {
            if (!ModelState.IsValid)
            {
                return View(paisVm);
            }
            var pais = _mapper.Map<Pais>(paisVm);
            if (_servicios.Existe(pais))
            {
                ModelState.AddModelError(string.Empty, "País existente!!!");
                return View(paisVm);
            }
            _servicios.Guardar(pais);
            TempData["Msg"] = "Registro editado satisfactoriamente!!!";
            return RedirectToAction("Index");

        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var pais = _servicios.GetPaisPorId(id.Value);
            if (pais == null)
            {
                return HttpNotFound("Código de país inesistente!!!");
            }
            var paisVm=_mapper.Map<PaisListVm>(pais);
            paisVm.CantidadCiudades = _serviciosCiudades
                .GetCantidad(c => c.PaisId == paisVm.PaisId);
            var paisDetailVm = new PaisDetailVm()
            {
                Pais = paisVm,
                Ciudades = _mapper.Map<List<CiudadListVm>>(
                _serviciosCiudades.GetCiudades(pais.PaisId))
            };
            return View(paisDetailVm);
        }

        public ActionResult AddCity(int? paisId)
        {
            if (paisId == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var pais = _servicios.GetPaisPorId(paisId.Value);
            if (pais == null)
            {
                return HttpNotFound("Código de país inesistente!!!");
            }
            var ciudadVm = new CiudadEditVm()
            {
                Paises = _servicios.GetPaisesDropDownList()
            };
            return View(ciudadVm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddCity(CiudadEditVm ciudadVm)
        {
            if (!ModelState.IsValid)
            {
                ciudadVm.Paises = _servicios.GetPaisesDropDownList();
                return View(ciudadVm);
            }
            try
            {
                var ciudad = _mapper.Map<Ciudad>(ciudadVm);
                if (!_serviciosCiudades.Existe(ciudad))
                {
                    _serviciosCiudades.Guardar(ciudad);
                    return RedirectToAction($"Details/{ciudad.PaisId}");
                }
                else
                {
                    ciudadVm.Paises = _servicios.GetPaisesDropDownList();
                    ModelState.AddModelError(string.Empty, "Ciudad existente!!!");
                    return View(ciudadVm);
                }
            }
            catch (Exception)
            {

                ciudadVm.Paises = _servicios.GetPaisesDropDownList();
                ModelState.AddModelError(string.Empty, "Error al intentar agregar una Ciudad");
                return View(ciudadVm);

            }
        }

        public ActionResult DeleteCity(int? id) {

            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var ciudad = _serviciosCiudades.GetCiudadPorId(id.Value);
            if (ciudad == null)
            {
                return HttpNotFound("Código de ciudad inesistente!!!");
            }
            var ciudadVm = _mapper.Map<CiudadEditVm>(ciudad);
            ciudadVm.Paises = _servicios.GetPaisesDropDownList();
            return View(ciudadVm);

        }
        [HttpPost, ActionName("DeleteCity")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteCityConfirm(int id)
        {
            var ciudad = _serviciosCiudades.GetCiudadPorId(id);
            var ciudadVm = _mapper.Map<CiudadEditVm>(ciudad);
            try
            {
                if (!_serviciosCiudades.EstaRelacionada(ciudad))
                {
                    _serviciosCiudades.Borrar(id);
                    return RedirectToAction($"Details/{ciudad.PaisId}");
                }
                else
                {
                    ciudadVm.Paises = _servicios.GetPaisesDropDownList();
                    ModelState.AddModelError(string.Empty, "Ciudad relacionada... Baja denegada");
                    return View(ciudadVm);
                }
            }
            catch (Exception)
            {

                ciudadVm.Paises = _servicios.GetPaisesDropDownList();
                ModelState.AddModelError(string.Empty, "Error al intentar borrar una ciudad");
                return View(ciudadVm);

            }
        }

        public ActionResult EditCity(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var ciudad = _serviciosCiudades.GetCiudadPorId(id.Value);
            if (ciudad == null)
            {
                return HttpNotFound("Código de ciudad inesistente!!!");
            }
            var ciudadVm = _mapper.Map<CiudadEditVm>(ciudad);
            ciudadVm.PaisAnteriorId = ciudad.PaisId;
            ciudadVm.Paises = _servicios.GetPaisesDropDownList();
            return View(ciudadVm);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCity(CiudadEditVm ciudadVm)
        {
            if (!ModelState.IsValid)
            {
                ciudadVm.Paises = _servicios.GetPaisesDropDownList();
                return View(ciudadVm);

            }
            try
            {
                var ciudad = _mapper.Map<Ciudad>(ciudadVm);
                if (!_serviciosCiudades.Existe(ciudad))
                {
                    _serviciosCiudades.Guardar(ciudad);
                    return RedirectToAction($"Details/{ciudadVm.PaisAnteriorId}");
                }
                else
                {

TiendaVirtual.Web/Controllers/VentasController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TiendaVirtual.Servicios.Interfaces;
using TiendaVirtual.Web.App_Start;
using TiendaVirtual.Web.ViewModels.DetalleVenta;
using TiendaVirtual.Web.ViewModels.Venta;

namespace TiendaVirtual.Web.Controllers
{
    public class VentasController : Controller
    {
        // GET: Ventas
        private readonly IServiciosVentas _servicio;
        private readonly IMapper _mapper;
        public VentasController(IServiciosVentas servicio)
        {
            _servicio = servicio;
            _mapper = AutoMapperConfig.Mapper;
        }
        public ActionResult Index()
        {
            var lista = _servicio.GetVentas();
            var listaVm=_mapper.Map<List<VentaListVm>>(lista);
            return View(listaVm);
        }

        public ActionResult Details(int? id)
        {
            if (id==null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }
            var venta = _servicio.GetVentasPorId(id.Value);
            if (venta==null)
            {
                return HttpNotFound("Código no encontrado");
            }
            var detalle = _servicio.GetDetalleVenta(id.Value);
            var detalleVm=_mapper.Map<List<DetalleVentaListVm>>(detalle);
            var ventaVm = new VentaDetailVm
            {
                Venta = _mapper.Map<VentaListVm>(venta),
                Detalles = detalleVm
            };
            return View(ventaVm);
        }
    }
}

TiendaVirtual.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Tienda Virtual Neptuno", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Archivos
                        </a>
                        <ul class="dropdown-menu">
                            @if (User.IsInRole("Admin"))
                            {
                                <li><a class="dropdown-item" href="@Url.Action("Index","Paises",new {area=string.Empty})">Países</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("Index","Ciudades",new {area=string.Empty})">Ciudades</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("Index","Clientes",new {area=string.Empty})">Clientes</a></li>
                                <li><hr class="dropdown-divider"></li>

                            }

                            <li><a class="dropdown-item" href="@Url.Action("Index","Categorias",new {area=string.Empty})">Categorías</a></li>
                            @if (User.IsInRole("Admin"))
                            {
                                <li><a class="dropdown-item" href="@Url.Action("Index","Proveedores",new {area=string.Empty})">Proveedores</a></li>

                            }
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="@Url.Action("Index","Productos",new {area=string.Empty})">Productos</a></li>

                        </ul>
                    </li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Ventas
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="@Url.Action("Index","Ventas",new {area=string.Empty})">Ventas</a></li>

                                <li><hr class="dropdown-divider"></li>

                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Seguridad
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="@Url.Action("Index","RolesAdmin",new {area="Identity"})">Roles</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("Index","UsersAdmin",new {area="Identity"})">Usuarios</a></li>

                            </ul>
                        </li>

                    }


                </ul>
            </div>
            @Html.Partial("_LoginPartial")
            @if (User.IsInRole("Cliente"))
            {
                @Html.Action("MostrarCarrito","Carrito")

            }
        </div>
    </nav>
    <div class="container body-content">
        @Html.Partial("_Notificacion")
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TiendaVirtual.Web/Views/Shared/_MostrarCarrito.cshtml
@model TiendaVirtual.Web.Models.Carrito.Carrito
@{ 
    string returnUrl = "Productos";
}
<form class="d-flex" action="@Url.Action("Index", "Carrito", new {returnUrl})">
    <button class="btn btn-outline-light" type="submit">
        <i class="fa fa-shopping-cart me-1"></i>
        Carrito
        <span class="badge bg-light text-dark ms-1 rounded-pill">@Model.GetCantidad()</span>
    </button>
</form>

TiendaVirtual.Web/Views/Shared/_MostrarCiudad.cshtml
@model TiendaVirtual.Web.ViewModels.Ciudad.CiudadEditVm
<div class="form-group">
    @Html.LabelFor(model => model.NombreCiudad, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-5">
        @Html.EditorFor(model => model.NombreCiudad, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.NombreCiudad, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.PaisId, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-5">
        @Html.DropDownListFor(model => model.PaisId, Model.Paises, "Seleccione País", new { @class = "form-select" })
        @Html.ValidationMessageFor(model => model.PaisId, "", new { @class = "text-danger" })
    </div>
</div>

TiendaVirtual.Web/Views/Shared/_MostrarCliente.cshtml
@model TiendaVirtual.Web.ViewModels.Cliente.ClienteEditVm
<div class="row">
    <div class="col-6">
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaisId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.PaisId, Model.Paises, "Seleccione País", new { @class = "form-select" })
                @Html.ValidationMessageFor(model => model.PaisId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CiudadId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CiudadId, Model.Ciudades, "Seleccione Ciudad", new { @class = "form-select" })
                @Html.ValidationMessageFor(model => model.CiudadId, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>
    <div class="col-6">
        <div class="form-group">
            @Html.LabelFor(model => model.CodPostal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CodPostal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CodPostal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TelefonoFijo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelefonoFijo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TelefonoFijo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TelefonoMovil, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelefonoMovil, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TelefonoMovil, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>
</div>

TiendaVirtual.Web/Views/Shared/_MostrarProveedor.cshtml
@model TiendaVirtual.Web.ViewModels.Proveedor.ProveedorEditVm
<div class="form-group">
    @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-5">
        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-5">
        @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.PaisId, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-5">
        @Html.DropDownListFor(model => model.PaisId, Model.Paises, "Seleccione País", new { @class = "form-select" })
        @Html.ValidationMessageFor(model => model.PaisId, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.CiudadId, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-5">
        @Html.DropDownListFor(model => model.CiudadId, Model.Ciudades, "Seleccione Ciudad", new { @class = "form-select" })
        @Html.ValidationMessageFor(model => model.CiudadId, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.CodPostal, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-5">
        @Html.EditorFor(model => model.CodPostal, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.CodPostal, "", new { @class = "text-danger" })
    </div>
</div>

TiendaVirtual.Web/Views/Shared/_Notificacion.cshtml
@if (TempData["Msg"] != null)
{
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/toastr.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Msg"]')
    </script>
}
@if (TempData["Error"] != null)
{
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/toastr.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["Error"]')
    </script>
}